CREATE DATABASE quizzes_api_v1;
GRANT ALL PRIVILEGES ON DATABASE quizzes_api_v1 TO quizzes_api;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO quizzes_api;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO quizzes_api;

SELECT
    
